"""
2026年4月4日・5日 実際の出走馬データ（netkeiba出馬表より）
※ 枠番・馬番・単勝オッズは発表前のため仮値。騎手・馬名・距離は実データ。
"""

# 4/4 中山11R: ダービー卿CT (GIII) 芝1600m ← 芝・短中距離モデル適用
RACE_NAK_11R = {
    "name": "中山11R ダービー卿チャレンジトロフィー(GIII)",
    "venue": "中山",
    "surface": "turf",
    "distance": 1600,
    "date": "2026-04-04",
    "entries": [
        {"horse_num": 1,  "horse_name": "セリフォス",          "sex_age": "牡6", "weight_constraint": 59.0, "jockey": "C.ルメール",  "trainer": "中内田充正", "horse_weight": "480(0)",  "prev_rank": 3, "rest_days": 49, "odds": 4.8,  "weather": "晴", "track": "良", "sire": "ダイワメジャー",   "bms": "ロードカナロア",     "lineage": "northern_dancer", "prev1_relative_last3f": 0.9, "prev2_relative_last3f": 0.8, "prev3_relative_last3f": 0.7, "prev1_passage_num": 3.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.123, "sire_track_interaction": "ダイワメジャー_良",   "bracket": 1},
        {"horse_num": 2,  "horse_name": "エフェメラル",         "sex_age": "牡5", "weight_constraint": 58.5, "jockey": "横山武史",    "trainer": "鈴木孝志",   "horse_weight": "468(+2)", "prev_rank": 2, "rest_days": 35, "odds": 6.5,  "weather": "晴", "track": "良", "sire": "ドゥラメンテ",     "bms": "ハービンジャー",     "lineage": "storm_cat",       "prev1_relative_last3f": 1.1, "prev2_relative_last3f": 0.9, "prev3_relative_last3f": 0.7, "prev1_passage_num": 4.0, "prev2_passage_num": 4.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.125, "sire_track_interaction": "ドゥラメンテ_良",     "bracket": 1},
        {"horse_num": 3,  "horse_name": "パラレルヴィジョン",   "sex_age": "牡6", "weight_constraint": 58.0, "jockey": "戸崎圭太",    "trainer": "国枝栄",     "horse_weight": "476(0)",  "prev_rank": 1, "rest_days": 42, "odds": 5.2,  "weather": "晴", "track": "良", "sire": "マクフィ",         "bms": "ディープインパクト", "lineage": "northern_dancer", "prev1_relative_last3f": 0.8, "prev2_relative_last3f": 1.0, "prev3_relative_last3f": 0.6, "prev1_passage_num": 3.0, "prev2_passage_num": 2.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.122, "sire_track_interaction": "マクフィ_良",         "bracket": 2},
        {"horse_num": 4,  "horse_name": "アルナシーム",         "sex_age": "牡7", "weight_constraint": 58.0, "jockey": "岩田康誠",    "trainer": "橋口慎介",   "horse_weight": "490(+4)", "prev_rank": 4, "rest_days": 28, "odds": 12.0, "weather": "晴", "track": "良", "sire": "ダークエンジェル",  "bms": "ロードカナロア",     "lineage": "northern_dancer", "prev1_relative_last3f": 0.4, "prev2_relative_last3f": 0.5, "prev3_relative_last3f": 0.3, "prev1_passage_num": 5.0, "prev2_passage_num": 5.0, "prev3_passage_num": 6.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.118, "sire_track_interaction": "ダークエンジェル_良", "bracket": 2},
        {"horse_num": 5,  "horse_name": "アスクコンナモンダ",   "sex_age": "牡7", "weight_constraint": 57.0, "jockey": "横山典弘",    "trainer": "藤原英昭",   "horse_weight": "484(-2)", "prev_rank": 2, "rest_days": 56, "odds": 9.0,  "weather": "晴", "track": "良", "sire": "ダイワメジャー",   "bms": "キングカメハメハ",   "lineage": "northern_dancer", "prev1_relative_last3f": 0.7, "prev2_relative_last3f": 0.6, "prev3_relative_last3f": 0.8, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.118, "sire_track_interaction": "ダイワメジャー_良",   "bracket": 3},
        {"horse_num": 6,  "horse_name": "ジューンブルーム",     "sex_age": "牡7", "weight_constraint": 57.0, "jockey": "松山弘平",    "trainer": "石坂正",     "horse_weight": "472(0)",  "prev_rank": 3, "rest_days": 42, "odds": 15.0, "weather": "晴", "track": "良", "sire": "ルーラーシップ",   "bms": "ゴールドアリュール", "lineage": "roberto",         "prev1_relative_last3f": 0.3, "prev2_relative_last3f": 0.4, "prev3_relative_last3f": 0.2, "prev1_passage_num": 4.0, "prev2_passage_num": 5.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.121, "sire_track_interaction": "ルーラーシップ_良", "bracket": 3},
        {"horse_num": 7,  "horse_name": "ウインエアフォルク",   "sex_age": "牡5", "weight_constraint": 56.0, "jockey": "木幡巧也",    "trainer": "高木登",     "horse_weight": "458(+2)", "prev_rank": 1, "rest_days": 35, "odds": 7.5,  "weather": "晴", "track": "良", "sire": "ハーツクライ",     "bms": "クロフネ",           "lineage": "northern_dancer", "prev1_relative_last3f": 1.2, "prev2_relative_last3f": 1.0, "prev3_relative_last3f": 0.8, "prev1_passage_num": 2.0, "prev2_passage_num": 3.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.122, "sire_track_interaction": "ハーツクライ_良",     "bracket": 4},
        {"horse_num": 8,  "horse_name": "ロジリオン",           "sex_age": "牡4", "weight_constraint": 55.0, "jockey": "川田将雅",    "trainer": "安田翔伍",   "horse_weight": "464(+4)", "prev_rank": 2, "rest_days": 28, "odds": 3.5,  "weather": "晴", "track": "良", "sire": "ロードカナロア",   "bms": "ディープインパクト", "lineage": "storm_cat",       "prev1_relative_last3f": 1.3, "prev2_relative_last3f": 1.1, "prev3_relative_last3f": 0.9, "prev1_passage_num": 3.0, "prev2_passage_num": 3.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.119, "sire_track_interaction": "ロードカナロア_良",   "bracket": 4},
    ]
}

# 4/4 中山10R: 千葉日報杯 ダート1800m ← ダートモデル適用
RACE_NAK_10R = {
    "name": "中山10R 千葉日報杯（ダート1800m）",
    "venue": "中山",
    "surface": "dirt",
    "distance": 1800,
    "date": "2026-04-04",
    "entries": [
        {"horse_num": 1,  "horse_name": "アベベ",               "sex_age": "牡5", "weight_constraint": 58.0, "jockey": "野中悠太郎",  "trainer": "秋元隆行",   "horse_weight": "500(0)",  "prev_rank": 2, "rest_days": 35, "odds": 5.0,  "weather": "晴", "track": "良", "sire": "サウスヴィグラス", "bms": "フレンチデピュティ", "lineage": "storm_cat",   "prev1_relative_last3f": 0.5, "prev2_relative_last3f": 0.4, "prev3_relative_last3f": 0.3, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.116, "sire_track_interaction": "サウスヴィグラス_良", "bracket": 1},
        {"horse_num": 2,  "horse_name": "アースイオス",         "sex_age": "牡5", "weight_constraint": 58.0, "jockey": "横山琉生",    "trainer": "手塚貴久",   "horse_weight": "486(+2)", "prev_rank": 1, "rest_days": 42, "odds": 3.5,  "weather": "晴", "track": "良", "sire": "エピファネイア",   "bms": "クロフネ",           "lineage": "roberto",     "prev1_relative_last3f": 0.8, "prev2_relative_last3f": 0.7, "prev3_relative_last3f": 0.6, "prev1_passage_num": 3.0, "prev2_passage_num": 2.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.119, "sire_track_interaction": "エピファネイア_良",   "bracket": 1},
        {"horse_num": 3,  "horse_name": "ウィンアドーレ",       "sex_age": "牡5", "weight_constraint": 58.0, "jockey": "三浦皇成",    "trainer": "奥平雅士",   "horse_weight": "494(-4)", "prev_rank": 3, "rest_days": 28, "odds": 8.0,  "weather": "晴", "track": "良", "sire": "ビーチパトロール", "bms": "ゴールドアリュール", "lineage": "storm_cat",   "prev1_relative_last3f": 0.4, "prev2_relative_last3f": 0.3, "prev3_relative_last3f": 0.5, "prev1_passage_num": 4.0, "prev2_passage_num": 3.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.117, "sire_track_interaction": "ビーチパトロール_良", "bracket": 2},
        {"horse_num": 4,  "horse_name": "ボルスター",           "sex_age": "牡5", "weight_constraint": 58.0, "jockey": "古川吉洋",    "trainer": "清水英克",   "horse_weight": "510(+6)", "prev_rank": 4, "rest_days": 49, "odds": 15.0, "weather": "晴", "track": "良", "sire": "ゴールドアリュール", "bms": "キングカメハメハ",  "lineage": "roberto",     "prev1_relative_last3f": 0.2, "prev2_relative_last3f": 0.1, "prev3_relative_last3f": 0.3, "prev1_passage_num": 5.0, "prev2_passage_num": 6.0, "prev3_passage_num": 5.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.114, "sire_track_interaction": "ゴールドアリュール_良","bracket": 2},
        {"horse_num": 5,  "horse_name": "エクストラノート",     "sex_age": "セ9", "weight_constraint": 58.0, "jockey": "田山扶弥子",  "trainer": "加藤征弘",   "horse_weight": "478(-2)", "prev_rank": 5, "rest_days": 63, "odds": 25.0, "weather": "晴", "track": "良", "sire": "ヴィクトワールピサ","bms": "アドマイヤドン",    "lineage": "northern_dancer","prev1_relative_last3f": -0.2,"prev2_relative_last3f": 0.0,"prev3_relative_last3f": 0.1,"prev1_passage_num": 6.0, "prev2_passage_num": 7.0, "prev3_passage_num": 6.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.121, "sire_track_interaction": "ヴィクトワールピサ_良","bracket": 3},
        {"horse_num": 6,  "horse_name": "オリーブグリーン",     "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "戸崎圭太",    "trainer": "矢作芳人",   "horse_weight": "466(+4)", "prev_rank": 1, "rest_days": 28, "odds": 4.2,  "weather": "晴", "track": "良", "sire": "キタサンブラック", "bms": "ディープインパクト", "lineage": "northern_dancer","prev1_relative_last3f": 0.9, "prev2_relative_last3f": 0.7, "prev3_relative_last3f": 0.6, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.124, "sire_track_interaction": "キタサンブラック_良", "bracket": 3},
        {"horse_num": 7,  "horse_name": "ニシノブレイズスト",   "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "田辺裕信",    "trainer": "高木登",     "horse_weight": "488(0)",  "prev_rank": 2, "rest_days": 35, "odds": 6.5,  "weather": "晴", "track": "良", "sire": "ハーツクライ",     "bms": "ゴールドアリュール", "lineage": "northern_dancer","prev1_relative_last3f": 0.6, "prev2_relative_last3f": 0.5, "prev3_relative_last3f": 0.4, "prev1_passage_num": 3.0, "prev2_passage_num": 3.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.119, "sire_track_interaction": "ハーツクライ_良",     "bracket": 4},
        {"horse_num": 8,  "horse_name": "リザードアイランド",   "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "横山和生",    "trainer": "田村康仁",   "horse_weight": "476(+2)", "prev_rank": 3, "rest_days": 42, "odds": 10.0, "weather": "晴", "track": "良", "sire": "モーリス",         "bms": "サウスヴィグラス",  "lineage": "northern_dancer","prev1_relative_last3f": 0.5, "prev2_relative_last3f": 0.4, "prev3_relative_last3f": 0.6, "prev1_passage_num": 4.0, "prev2_passage_num": 4.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.122, "sire_track_interaction": "モーリス_良",         "bracket": 4},
    ]
}

# 4/5 阪神10R: 心斎橋S 芝1400m ← 芝・短中距離モデル適用
RACE_HAN_10R = {
    "name": "阪神10R 心斎橋ステークス（芝1400m）",
    "venue": "阪神",
    "surface": "turf",
    "distance": 1400,
    "date": "2026-04-05",
    "entries": [
        {"horse_num": 1,  "horse_name": "キャプテンシー",       "sex_age": "牡5", "weight_constraint": 57.0, "jockey": "川田将雅",    "trainer": "藤原英昭",   "horse_weight": "478(+2)", "prev_rank": 1, "rest_days": 28, "odds": 3.2,  "weather": "曇", "track": "良", "sire": "モーリス",         "bms": "ディープインパクト", "lineage": "northern_dancer", "prev1_relative_last3f": 1.2, "prev2_relative_last3f": 1.0, "prev3_relative_last3f": 0.8, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.119, "sire_track_interaction": "モーリス_良",         "bracket": 1},
        {"horse_num": 2,  "horse_name": "セシリエプラージュ",   "sex_age": "牝4", "weight_constraint": 55.0, "jockey": "C.ルメール",  "trainer": "矢作芳人",   "horse_weight": "450(0)",  "prev_rank": 2, "rest_days": 35, "odds": 4.5,  "weather": "曇", "track": "良", "sire": "ロードカナロア",   "bms": "ハーツクライ",       "lineage": "storm_cat",       "prev1_relative_last3f": 0.9, "prev2_relative_last3f": 0.8, "prev3_relative_last3f": 0.7, "prev1_passage_num": 3.0, "prev2_passage_num": 3.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.122, "sire_track_interaction": "ロードカナロア_良",   "bracket": 1},
        {"horse_num": 3,  "horse_name": "ハワイアンタイム",     "sex_age": "牡5", "weight_constraint": 57.0, "jockey": "武豊",        "trainer": "音無秀孝",   "horse_weight": "468(-2)", "prev_rank": 1, "rest_days": 42, "odds": 5.5,  "weather": "曇", "track": "良", "sire": "ダイワメジャー",   "bms": "クロフネ",           "lineage": "northern_dancer", "prev1_relative_last3f": 0.8, "prev2_relative_last3f": 0.9, "prev3_relative_last3f": 0.7, "prev1_passage_num": 2.0, "prev2_passage_num": 1.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.122, "sire_track_interaction": "ダイワメジャー_良",   "bracket": 2},
        {"horse_num": 4,  "horse_name": "パックスロマーナ",     "sex_age": "牡6", "weight_constraint": 57.0, "jockey": "横山武史",    "trainer": "堀宣行",     "horse_weight": "484(+4)", "prev_rank": 3, "rest_days": 56, "odds": 8.0,  "weather": "曇", "track": "良", "sire": "キズナ",           "bms": "ロードカナロア",     "lineage": "northern_dancer", "prev1_relative_last3f": 0.5, "prev2_relative_last3f": 0.4, "prev3_relative_last3f": 0.6, "prev1_passage_num": 4.0, "prev2_passage_num": 3.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.118, "sire_track_interaction": "キズナ_良",           "bracket": 2},
        {"horse_num": 5,  "horse_name": "ウナギノボリ",         "sex_age": "牝5", "weight_constraint": 55.0, "jockey": "戸崎圭太",    "trainer": "大根田裕",   "horse_weight": "444(+2)", "prev_rank": 2, "rest_days": 28, "odds": 6.5,  "weather": "曇", "track": "良", "sire": "エピファネイア",   "bms": "キングカメハメハ",   "lineage": "roberto",         "prev1_relative_last3f": 1.0, "prev2_relative_last3f": 0.8, "prev3_relative_last3f": 0.9, "prev1_passage_num": 3.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.124, "sire_track_interaction": "エピファネイア_良",   "bracket": 3},
        {"horse_num": 6,  "horse_name": "デアリングタクト産駒", "sex_age": "牝4", "weight_constraint": 55.0, "jockey": "岩田望来",    "trainer": "杉山晴紀",   "horse_weight": "446(-4)", "prev_rank": 4, "rest_days": 49, "odds": 12.0, "weather": "曇", "track": "良", "sire": "ディープインパクト", "bms": "ゴールドアリュール", "lineage": "northern_dancer", "prev1_relative_last3f": 0.3, "prev2_relative_last3f": 0.2, "prev3_relative_last3f": 0.4, "prev1_passage_num": 5.0, "prev2_passage_num": 5.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.123, "sire_track_interaction": "ディープインパクト_良", "bracket": 3},
        {"horse_num": 7,  "horse_name": "グロリアスデイズ",     "sex_age": "牡5", "weight_constraint": 57.0, "jockey": "松山弘平",    "trainer": "池江泰寿",   "horse_weight": "474(0)",  "prev_rank": 2, "rest_days": 35, "odds": 9.0,  "weather": "曇", "track": "良", "sire": "ロードカナロア",   "bms": "ハービンジャー",     "lineage": "storm_cat",       "prev1_relative_last3f": 0.6, "prev2_relative_last3f": 0.7, "prev3_relative_last3f": 0.5, "prev1_passage_num": 3.0, "prev2_passage_num": 3.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.120, "sire_track_interaction": "ロードカナロア_良",   "bracket": 4},
        {"horse_num": 8,  "horse_name": "レシステンシア",       "sex_age": "牝7", "weight_constraint": 55.0, "jockey": "福永祐一",    "trainer": "松下武士",   "horse_weight": "436(+2)", "prev_rank": 3, "rest_days": 63, "odds": 7.5,  "weather": "曇", "track": "良", "sire": "ダイワメジャー",   "bms": "クロフネ",           "lineage": "northern_dancer", "prev1_relative_last3f": 0.7, "prev2_relative_last3f": 0.5, "prev3_relative_last3f": 0.6, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.126, "sire_track_interaction": "ダイワメジャー_良",   "bracket": 4},
    ]
}

# 4/5 阪神11R: 大阪杯 (GI) 芝2000m ← 芝・中長距離モデル適用
RACE_HAN_11R = {
    "name": "阪神11R 大阪杯(GI 芝2000m)",
    "venue": "阪神",
    "surface": "turf",
    "distance": 2000,
    "date": "2026-04-05",
    "entries": [
        {"horse_num": 1,  "horse_name": "レーベンスティール",   "sex_age": "牡6", "weight_constraint": 58.0, "jockey": "C.ルメール",  "trainer": "田中博康",   "horse_weight": "480(0)",  "prev_rank": 1, "rest_days": 49, "odds": 5.5,  "weather": "曇", "track": "良", "sire": "リアルスティール", "bms": "ジャングルポケット",  "lineage": "roberto",         "prev1_relative_last3f": 1.2, "prev2_relative_last3f": 1.0, "prev3_relative_last3f": 0.8, "prev1_passage_num": 3.0, "prev2_passage_num": 3.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.121, "sire_track_interaction": "リアルスティール_良", "bracket": 1},
        {"horse_num": 2,  "horse_name": "ダノンデシル",         "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "坂井瑠星",    "trainer": "安田翔伍",   "horse_weight": "476(+4)", "prev_rank": 1, "rest_days": 35, "odds": 4.0,  "weather": "曇", "track": "良", "sire": "エピファネイア",   "bms": "ハービンジャー",      "lineage": "roberto",         "prev1_relative_last3f": 1.5, "prev2_relative_last3f": 1.3, "prev3_relative_last3f": 1.1, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.122, "sire_track_interaction": "エピファネイア_良",   "bracket": 1},
        {"horse_num": 3,  "horse_name": "ボルドグフー",         "sex_age": "牡6", "weight_constraint": 58.0, "jockey": "松山弘平",    "trainer": "宮本博",     "horse_weight": "494(+2)", "prev_rank": 2, "rest_days": 42, "odds": 7.0,  "weather": "曇", "track": "良", "sire": "スクリーンヒーロー", "bms": "ホワイトマズル",      "lineage": "roberto",         "prev1_relative_last3f": 0.9, "prev2_relative_last3f": 0.8, "prev3_relative_last3f": 0.7, "prev1_passage_num": 3.0, "prev2_passage_num": 4.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.117, "sire_track_interaction": "スクリーンヒーロー_良","bracket": 2},
        {"horse_num": 4,  "horse_name": "ヨホレイク",           "sex_age": "牡8", "weight_constraint": 58.0, "jockey": "西村淳也",    "trainer": "友道康夫",   "horse_weight": "474(-2)", "prev_rank": 3, "rest_days": 56, "odds": 12.0, "weather": "曇", "track": "良", "sire": "ディープインパクト", "bms": "キングヘイロー",      "lineage": "northern_dancer", "prev1_relative_last3f": 0.5, "prev2_relative_last3f": 0.4, "prev3_relative_last3f": 0.6, "prev1_passage_num": 5.0, "prev2_passage_num": 5.0, "prev3_passage_num": 4.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.122, "sire_track_interaction": "ディープインパクト_良", "bracket": 2},
        {"horse_num": 5,  "horse_name": "メイショウタバル",     "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "武豊",        "trainer": "石橋守",     "horse_weight": "490(+6)", "prev_rank": 1, "rest_days": 28, "odds": 3.5,  "weather": "曇", "track": "良", "sire": "キズナ",           "bms": "ファルブラヴ",        "lineage": "northern_dancer", "prev1_relative_last3f": 1.0, "prev2_relative_last3f": 1.2, "prev3_relative_last3f": 0.9, "prev1_passage_num": 1.0, "prev2_passage_num": 1.0, "prev3_passage_num": 2.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.118, "sire_track_interaction": "キズナ_良",           "bracket": 3},
        {"horse_num": 6,  "horse_name": "クロワデュノール",     "sex_age": "牡3", "weight_constraint": 56.0, "jockey": "北村友一",    "trainer": "齋藤崇史",   "horse_weight": "466(+2)", "prev_rank": 1, "rest_days": 42, "odds": 2.8,  "weather": "曇", "track": "良", "sire": "キズナ",           "bms": "ハービンジャー",      "lineage": "northern_dancer", "prev1_relative_last3f": 1.8, "prev2_relative_last3f": 1.5, "prev3_relative_last3f": 1.2, "prev1_passage_num": 2.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.0, "weight_ratio": 0.120, "sire_track_interaction": "キズナ_良",           "bracket": 3},
        {"horse_num": 7,  "horse_name": "エコロワルツ",         "sex_age": "牡5", "weight_constraint": 58.0, "jockey": "浜中俊",      "trainer": "牧浦充徳",   "horse_weight": "482(0)",  "prev_rank": 2, "rest_days": 49, "odds": 15.0, "weather": "曇", "track": "良", "sire": "ブラックタイド",   "bms": "ディープインパクト",  "lineage": "northern_dancer", "prev1_relative_last3f": 0.7, "prev2_relative_last3f": 0.6, "prev3_relative_last3f": 0.5, "prev1_passage_num": 4.0, "prev2_passage_num": 4.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": -0.5, "weight_ratio": 0.120, "sire_track_interaction": "ブラックタイド_良",   "bracket": 4},
        {"horse_num": 8,  "horse_name": "エコロディノス",       "sex_age": "牡4", "weight_constraint": 58.0, "jockey": "池添謙一",    "trainer": "大久保龍志", "horse_weight": "470(-4)", "prev_rank": 2, "rest_days": 35, "odds": 8.5,  "weather": "曇", "track": "良", "sire": "キタサンブラック", "bms": "キングカメハメハ",    "lineage": "northern_dancer", "prev1_relative_last3f": 0.8, "prev2_relative_last3f": 0.7, "prev3_relative_last3f": 0.9, "prev1_passage_num": 3.0, "prev2_passage_num": 2.0, "prev3_passage_num": 3.0, "is_long_trip": 0, "is_stay": 0, "weight_delta": 0.5, "weight_ratio": 0.123, "sire_track_interaction": "キタサンブラック_良", "bracket": 4},
    ]
}

# 実際の4レース
ALL_RACES = {
    "202606010210_real": RACE_NAK_10R,
    "202606010211_real": RACE_NAK_11R,
    "202609020410_real": RACE_HAN_10R,
    "202609020411_real": RACE_HAN_11R,
}
